# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, default='sin_imagen.jpg', null=True, upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ferre.Image'),
        ),
    ]
