# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferre', '0002_auto_20161013_1055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageProducto',
        ),
    ]
